# Generated by Django 5.0.7 on 2024-08-01 14:59

from django.db import migrations

def create_default_opciones(apps, schema_editor):
    Opciones = apps.get_model('inventario', 'Opciones')
    if not Opciones.objects.exists():
        Opciones.objects.create(
            moneda='$',
            valor_iva=15,
            nombre_negocio='Mi Negocio',
            mensaje_factura='Gracias por su compra'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_opciones),
    ]
