# Generated by Django 5.0.7 on 2024-08-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20240801_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoCedula',
            field=models.CharField(choices=[('1', 'Cédula de Identidad'), ('2', 'Pasaporte'), ('3', 'Cédula de Identidad para Extranjeros')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipoCedula',
            field=models.CharField(choices=[('1', 'Cédula de Identidad'), ('2', 'Pasaporte'), ('3', 'Cédula de Identidad para Extranjeros')], default='1', max_length=1),
        ),
    ]
