# Generated by Django 5.0.7 on 2024-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_descuento_factura_descuento_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marcas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
