# Generated by Django 5.0.7 on 2024-07-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_cliente_id_alter_detallefactura_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otro')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(choices=[('1', 'Unidad'), ('2', 'Kilo'), ('3', 'Litro'), ('4', 'Otros')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(default='0000000000000', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
    ]
